### PR TITLE
Hat support v2.5

### PR DESCRIPTION
**Pull request by tiandahuang**
# Quality Assurance Checklist
To make reviews more efficient, please make sure the board meets the following standards and check everything off once the board meets the quality check. Once everything has been checked, the assigned reviewers will begin the review process. _Edit this description to check off the list._

There are exceptions with all guidelines. As long as your decisions are justified, then you are good! Contact the reviewers or the leads about any exceptions.

## Minimum Prerequisites
- [x] The board passes ERC and DRC.
    - Note some ERC warnings are acceptable.
- [ ] All traces are routed.
- [x] Units are in metric.

## Schematic Level Requirements 
- [x] Is proper noise resistance given to all peripheral devices (bypass caps and coils/ferrites)?  
- [x] Is proper ESD protection given to all MCU input pins (zener diodes)?  
- [x] Is proper power protection given to peripheral devices (zener diodes)?  
- [x] Are peripheral units used properly (reading datasheet)?  
- [x] Are testing points added at useful places?  
- [x] Is there proper short to GND protection at MCU outputs (inline resistors)?  
- [x] Do ADC inputs have caps?  
- [x] Are ADC inputs biased so there is room above expected value to determine if value is being overflowed?  
- [x] Are LED's located at useful places (comm, power, debugging, extra GPIO)?  
- [x] Are parts chosen easy to collect?  
- [x] Are parts chosen easy to solder?  
- [x] Is there reverse polarity protection on inputs?  
### 2D Spacing
- [ ] The components are spaced out at an optimal distance.
    - All components can be easily hand-soldered.
    - IPC-SM-782A Standard requires a minimum distance of 1.0mm from edge to edge.
- [ ] Components that are in parallel with each other are spaced out at an equal distance when possible.
- [ ] The components are aligned with each other when possible.
- [ ] Components are grouped based off of functionality.
    - E.g. all components for CAN should be grouped.
- [ ] Bypass capacitors are less than 1cm away from their respective IC's power pins.

### 3D Spacing
- [ ] Layout of components have been placed with mounting location and usage of the board in mind.
    - Are PCBs going to be stacked on above/below this board? Are tall components placed accordingly?
    - Are buttons and lights easily accessible and viewable?
    - When mounted into the car, are the heights of the components and connectors accounted for?
- [ ] Location of connectors and wires going out of the board will prevent messy wiring.
    - Are all the wires that are going in the same direction placed on the same edge of the board?

### Components
- [ ] Custom footprints have been double checked with the datasheet.
- [ ] Pin 1 of the footprint is labeled in some way. 
- [ ] Are LED's in easy to see places? 
- [ ] Are test points in easy to reach places?  
- [ ] Are critical paths of switching converters as small as possible?  

### Copper Layer 
- [ ] The trace widths and trace clearances are greater than JLCPCB's minimum requirements. 
    - [ ] Are signal traces 6mils unless provided with reasoning?   
        - NOTE: One net can have multiple trace widths  
- [ ] The trace lengths are as short as possible. 
    - Can there be a more optimal route if you go to another layer? 
- [ ] Each trace's width is capable of handling the expected current flow. 
    - Use PCB width calculator to calculate trace width. 
- [ ] *No sharp corners. No trace angles equal to or less than 90 degrees. 
    - Orthogonal traces should have vias if necessary. 
- [ ] Are edges of board surrounded by clean ground on both layers with stitching vias?  
- [ ] Traces are in parallel with each other when possible. 
    - E.g. traces connected between an IC and MCU can be placed in parallel with each other. 
- [ ] There are no random trace appendages. 
- [ ] Vias placed in copper pads are fully encompassed in the copper pads. 
- [ ] Through-hole components do not have extraneous vias. 

*Not really a problem for modern manufacturing techniques but good practice and important for high speed signal integrity.

### Silkscreen Layer
- [ ] Visible text sizes are greater than JLCPCB's minimum requirements.
- [ ] All visible text is on the silkscreen layer.
- [ ] All reference labels of each component are not overlapping a copper pad or another component.
- [ ] All connector pins are labeled with a meaningful and helpful name.
- [ ] All LEDs are labeled with a meaningful and helpful name.
- [ ] Silkscreens are mostly facing one direction (or 2). 

### Edge Cut Layer
- [ ] The dimensions of the board and the mounting holes are nice values in metric i.e. no long decimals.
- [ ] The physical outline of the board is on the edge cut layer.
- [ ] Edge cuts are straight and parallel with opposite edge of the board.
- [ ] Mounting holes are aligned.
- [ ] Corners are curved and contoured to mounting holes.

### IMPORTANT NOTICE
- [ ] I am confident that this board will be safe to use in a safety critical environment.
- [ ] I had fun :)

## Other Comments
_Write any comments about the board that would help the reviewers here._

### CODE REVIEW

**Comment by manthanand** [comment]
Can you make a BOM and make sure that it isn't ignored in the .gitignore file? Also, update the PCB QAC with the one in OneNote. Create a mouser cart with the components needed and put the link in the BOM. Also, have you picked out a shield for the board? You would need mounting for that.

**Comment by manthanand** [comment]
image
image
If you have the dirty ground on the bottom which will be exposed to the noise on the high voltage line being used as a reference for analog circuitry, would it really provide any noise protection? I think it is just this one component that would be affected so you could just add a ferrite bead from gnd to the input pin.

**Comment by manthanand** [comment]
Also replace hannah's name with urs in the board design.

**Comment by tiandahuang** [comment]
> If you have the dirty ground on the bottom which will be exposed to the noise on the high voltage line being used as a reference for analog circuitry, would it really provide any noise protection? I think it is just this one component that would be affected so you could just add a ferrite bead from gnd to the input pin.

Could add a pi-filter at analog grounds or I think fencing with vias is a valid option

**Comment by manthanand** [comment]
> > If you have the dirty ground on the bottom which will be exposed to the noise on the high voltage line being used as a reference for analog circuitry, would it really provide any noise protection? I think it is just this one component that would be affected so you could just add a ferrite bead from gnd to the input pin.
> 
> Could add a pi-filter at analog grounds or I think fencing with vias is a valid option

Whatever u wanna, as long as there is something.

**Comment by manthanand** [comment]
image
Should keep these widths consistent (they could use the smaller one since that IC won't need too much current).

**Comment by manthanand** [comment]
image
Do something similar for the analog positive reference as well.

**Comment by manthanand** [comment]
image
I would prefer it if the filtering circuitry for 3V was on the top side and not the bottom along with being on the path towards the IC. If there is a spike, then idk if the filtering circuitry would do much to stop it since low impedance path would be straight through the via. Or you could leave the cap on the bottom but just have it on the path.

**Comment by HannahSLee14** [comment]
It looks good! Just a few comments:
- If this is just a physical connector, why are there labels for each of these connections?
image
- The power and gnd testpoints are really close together - not sure if we are worried about these accidentally shorting
image
image
- The +12V trace and GNDPWR pad are very close together
imageDo
- Do we want to add the pad connections to solid fill instead of thermal relief? It'll change these cross patterns to be a solid connection on all sides
image
image
- Label all the connections on J1 and J2? I know that it may be a spacing problem 
- I see that some of the labels (D1, R2, R4, etc.) are kept hidden/invisible. Is this going to be okay? Will this make testing or debugging difficult?
- I know the isoSPI chip and signals are a bit picky with having signals or gnd places underneath it. Is the gnd plane and the components underneath IP and IM here going to be an issue?
image
-  I think it'll be helpful to label any LEDs (e.g. D1)

**Comment by manthanand** [comment]
In terms of the labels, those connectors are going to be jumpers for either testing the shunt or using the shunt boars, so the labels are for what the connections would be (if there was a jumper). I think thermal reliefs are fine since soldering will be really difficult if the entire pad was solid on the plane (heating up the entire plane instead of just a pad).

**Comment by tiandahuang** [comment]
addressed some of the silkscreen concerns... most parts will still be unlabeled due to spacing issues, and there's only one led on the board (all other d# are normal diodes)

also fixed the gnd plane around isospi

**Comment by tiandahuang** [comment]
also fixed the gnd plane around isospi

**Pull request merged**
